services:
  - type: web
    name: backend-1-1-p7wr
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DB_HOST
        value: dpg-d4a6g6buibrs73c8av30-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: wetoo_user
      - key: DB_PASS
        value: KsHHuF2UrOXSfHzG9B72BvyrjA0BJ1fc
      - key: DB_NAME
        value: wetoo
      - key: DB_SSL
        value: true
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: kalyankumar.muli64@gmail.com
      - key: SMTP_PASS
        value: nnrt ednr glyh wrwz
      - key: EMAIL_FROM
        value: WE TOO <kalyankumar.muli64@gmail.com>